import {Parrot} from './parrot';

export const PARROTS: Parrot[] = [
    { id: 0, name: 'aussiecongaparrot', path: 'img/aussiecongaparrot.gif' },
    { id: 1, name: 'aussieparrot', path: 'img/aussieparrot.gif' },
    { id: 2, name: 'aussiereversecongaparrot', path: 'img/aussiereversecongaparrot.gif' },
    { id: 3, name: 'boredparrot', path: 'img/boredparrot.gif' },
    { id: 4, name: 'chillparrot', path: 'img/chillparrot.gif' },
    { id: 5, name: 'congaparrot', path: 'img/congaparrot.gif' },
    { id: 6, name: 'dealwithitparrot', path: 'img/dealwithitparrot.gif' },
    { id: 7, name: 'explodyparrot', path: 'img/explodyparrot.gif' },
    { id: 8, name: 'fastparrot', path: 'img/fastparrot.gif' },
    { id: 9, name: 'fiestaparrot', path: 'img/fiestaparrot.gif' },
    { id: 10, name: 'gothparrot', path: 'img/gothparrot.gif' },
    { id: 11, name: 'ice-cream-parrot', path: 'img/ice-cream-parrot.gif' },
    { id: 12, name: 'middleparrot', path: 'img/middleparrot.gif' },
    { id: 13, name: 'oldtimeyparrot', path: 'img/oldtimeyparrot.gif' },
    { id: 14, name: 'parrot', path: 'img/parrot.gif' },
    { id: 15, name: 'parrotcop', path: 'img/parrotcop.gif' },
    { id: 16, name: 'parrotdad', path: 'img/parrotdad.gif' },
    { id: 17, name: 'parrotwave1', path: 'img/parrotwave1.gif' },
    { id: 18, name: 'parrotwave2', path: 'img/parrotwave2.gif' },
    { id: 19, name: 'parrotwave3', path: 'img/parrotwave3.gif' },
    { id: 20, name: 'parrotwave4', path: 'img/parrotwave4.gif' },
    { id: 21, name: 'parrotwave5', path: 'img/parrotwave5.gif' },
    { id: 22, name: 'parrotwave6', path: 'img/parrotwave6.gif' },
    { id: 23, name: 'parrotwave7', path: 'img/parrotwave7.gif' },
    { id: 24, name: 'partyparrot', path: 'img/partyparrot.gif' },
    { id: 25, name: 'reversecongaparrot', path: 'img/reversecongaparrot.gif' },
    { id: 26, name: 'rightparrot', path: 'img/rightparrot.gif' },
    { id: 27, name: 'sadparrot', path: 'img/sadparrot.gif' },
    { id: 28, name: 'shufflefurtherparrot', path: 'img/shufflefurtherparrot.gif' },
    { id: 29, name: 'shuffleparrot', path: 'img/shuffleparrot.gif' },
    { id: 30, name: 'shufflepartyparrot', path: 'img/shufflepartyparrot.gif' },
    { id: 31, name: 'slowparrot', path: 'img/slowparrot.gif' }
]